name: Curing Wendigo
favicon: null
layout_spectrum: 0.8431675522588193
typography_spectrum: 0.2577039038296789
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.3904209032189101
  lightness: 0.18803006783127785
  saturation: 0.0863631796091795
  rhythmicContrast: 0.9329854915849864
purpose: []
