name: Curing Wendigo
favicon: null
layout_spectrum: 0.2059
typography_spectrum: 0.07457
title: Curing Wendigo
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#607031'
    - '#4ea5af'
    - '#a7cfd6'
    - '#929a75'
  brandStrength: 0.875
  lightness: 0.5122554884292185
  saturation: 0.17873228690586984
  rhythmicContrast: 0.5742561011575162
purpose: []
